// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package downloadsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DownloadServiceClient is the client API for DownloadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DownloadServiceClient interface {
	CreateDownload(ctx context.Context, in *CreateDownloadRequest, opts ...grpc.CallOption) (*CreateDownloadResponse, error)
	DeleteDownload(ctx context.Context, in *DeleteDownloadRequest, opts ...grpc.CallOption) (*DeleteDownloadResponse, error)
	GetDownloads(ctx context.Context, in *GetDownloadsRequest, opts ...grpc.CallOption) (*GetDownloadsResponse, error)
}

type downloadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDownloadServiceClient(cc grpc.ClientConnInterface) DownloadServiceClient {
	return &downloadServiceClient{cc}
}

func (c *downloadServiceClient) CreateDownload(ctx context.Context, in *CreateDownloadRequest, opts ...grpc.CallOption) (*CreateDownloadResponse, error) {
	out := new(CreateDownloadResponse)
	err := c.cc.Invoke(ctx, "/downloads.v1.DownloadService/CreateDownload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *downloadServiceClient) DeleteDownload(ctx context.Context, in *DeleteDownloadRequest, opts ...grpc.CallOption) (*DeleteDownloadResponse, error) {
	out := new(DeleteDownloadResponse)
	err := c.cc.Invoke(ctx, "/downloads.v1.DownloadService/DeleteDownload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *downloadServiceClient) GetDownloads(ctx context.Context, in *GetDownloadsRequest, opts ...grpc.CallOption) (*GetDownloadsResponse, error) {
	out := new(GetDownloadsResponse)
	err := c.cc.Invoke(ctx, "/downloads.v1.DownloadService/GetDownloads", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DownloadServiceServer is the server API for DownloadService service.
// All implementations must embed UnimplementedDownloadServiceServer
// for forward compatibility
type DownloadServiceServer interface {
	CreateDownload(context.Context, *CreateDownloadRequest) (*CreateDownloadResponse, error)
	DeleteDownload(context.Context, *DeleteDownloadRequest) (*DeleteDownloadResponse, error)
	GetDownloads(context.Context, *GetDownloadsRequest) (*GetDownloadsResponse, error)
	mustEmbedUnimplementedDownloadServiceServer()
}

// UnimplementedDownloadServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDownloadServiceServer struct {
}

func (UnimplementedDownloadServiceServer) CreateDownload(context.Context, *CreateDownloadRequest) (*CreateDownloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDownload not implemented")
}
func (UnimplementedDownloadServiceServer) DeleteDownload(context.Context, *DeleteDownloadRequest) (*DeleteDownloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDownload not implemented")
}
func (UnimplementedDownloadServiceServer) GetDownloads(context.Context, *GetDownloadsRequest) (*GetDownloadsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDownloads not implemented")
}
func (UnimplementedDownloadServiceServer) mustEmbedUnimplementedDownloadServiceServer() {}

// UnsafeDownloadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DownloadServiceServer will
// result in compilation errors.
type UnsafeDownloadServiceServer interface {
	mustEmbedUnimplementedDownloadServiceServer()
}

func RegisterDownloadServiceServer(s grpc.ServiceRegistrar, srv DownloadServiceServer) {
	s.RegisterService(&DownloadService_ServiceDesc, srv)
}

func _DownloadService_CreateDownload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDownloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DownloadServiceServer).CreateDownload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/downloads.v1.DownloadService/CreateDownload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DownloadServiceServer).CreateDownload(ctx, req.(*CreateDownloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DownloadService_DeleteDownload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDownloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DownloadServiceServer).DeleteDownload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/downloads.v1.DownloadService/DeleteDownload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DownloadServiceServer).DeleteDownload(ctx, req.(*DeleteDownloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DownloadService_GetDownloads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDownloadsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DownloadServiceServer).GetDownloads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/downloads.v1.DownloadService/GetDownloads",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DownloadServiceServer).GetDownloads(ctx, req.(*GetDownloadsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DownloadService_ServiceDesc is the grpc.ServiceDesc for DownloadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DownloadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "downloads.v1.DownloadService",
	HandlerType: (*DownloadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDownload",
			Handler:    _DownloadService_CreateDownload_Handler,
		},
		{
			MethodName: "DeleteDownload",
			Handler:    _DownloadService_DeleteDownload_Handler,
		},
		{
			MethodName: "GetDownloads",
			Handler:    _DownloadService_GetDownloads_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "downloads/v1/downloads.proto",
}
