name: Lint
on:
  push:
permissions:
  contents: read
  checks: write
  statuses: write
jobs:
  golangci-lint:
    name: Golang CI Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - uses: actions/checkout@v3
      - run: mkdir cmd/ingress/public && touch cmd/ingress/public/index.html
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.2